name: gen

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  generation:
    name: generate metadata
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        working-directory: ./metadata
        run: dotnet build
      - name: Check
        run: |
          git add -N .
          git diff --exit-code || (echo '::error::Generated `tool_windows_app` is out-of-date. Please run `cargo run -p tool_windows_app`'; exit 1)
