name: test

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - version: stable
            target: x86_64-pc-windows-msvc
          - version: nightly
            target: i686-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.version }} && rustup default ${{ matrix.version }}-${{ matrix.target }}
      - name: Add toolchain target
        run: rustup target add ${{ matrix.target }}
      - name: Install clippy
        run: rustup component add clippy
      - name: Test
        run: >
          cargo test -p windows_app &&
          cargo test -p windows_app_deploy &&
          cargo test -p sample_appwindow &&
          cargo test -p sample_battery &&
          cargo test -p sample_colors &&
          cargo test -p sample_mrm &&
          cargo test -p sample_xamlapp &&
          cargo test -p test_dwritecore &&
          cargo test -p test_interop